name: "Build and deploy"

on:
  workflow_call:
    inputs:
      ecr_repo_url:
        description: 'URL to AWS ECR repository.'
        type: string
        required: true
      build_target:
        description: 'Define build target.'
        required: true
        type: string
      dockerfile:
        description: 'Define path and name of the Dockerfile.'
        type: string
        required: false
        default: './Dockerfile'
      push_docker_image:
        description: 'Set dry-run if false.'
        required: false
        type: boolean
        default: true
      deploy:
        description: 'Set dry-run if false.'
        required: false
        type: boolean
        default: true
      override_project:
        description: 'Define name of the project. If not set, then project will be taken from the step (Update argo) list.'
        required: false
        type: string

jobs:
  set_env:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_env.outputs.tag }}
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment
        id: set_env
        run: |
          if [[ ${{ github.ref_type }} == 'tag' ]];then
            tag=${{ github.ref_name }}
            environment='["rp2","staging","production"]'
          else
            tag=$(echo ${{ github.sha }} | cut -c1-8)
            environment='["rp2", "staging"]'
          fi
          echo "tag=${tag}" >> ${GITHUB_OUTPUT}
          echo "environment=$(jq -cr <<< "$environment")" >> $GITHUB_OUTPUT

  build:
    needs: [set_env]

    uses: millicast/github-actions/.github/workflows/kaniko.yml@v0.0.8
    with:
      ecr_repo_url: ${{ inputs.ecr_repo_url }}
      tag: ${{ needs.set_env.outputs.tag }}
      dockerfile: ${{ inputs.dockerfile}}
      push: ${{ inputs.push_docker_image }}
      dotnet_project: true
      build_target: ${{ inputs.build_target }}
    secrets: inherit

  deploy:
    needs: [set_env, build]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        environment: ${{ fromJson(needs.set_env.outputs.environment) }}

    uses: millicast/github-actions/.github/workflows/deploy.yml@v0.0.8
    with:
      environment: ${{ matrix.environment }}
      tag: ${{ needs.set_env.outputs.tag }}
      push: ${{ inputs.deploy }}
      override_project: ${{ inputs.override_project }}
    secrets: inherit
