name: Update docker image url in the helm deployment repository

on:
  workflow_call:
    inputs:
      environment:
        description: 'Define deployment environment.'
        required: true
        type: string
      tag:
        description: 'Tag of the docker image for helm deployment.'
        required: true
        type: string
      override_project:
        description: 'Define name of the project. If not set, then project will be taken from the step (Update argo) list.'
        required: false
        type: string
      push:
        description: 'Set dry-run if false.'
        required: false
        type: boolean
        default: true
      is_cronjob:
        description: 'Specify if service to deploy is a cronjob - enables deployment specificities.'
        required: false
        type: boolean
        default: false

jobs:
  argo_update:
    runs-on: [rts-dind]
    container: alpine/git
    environment: ${{ inputs.environment }}
    steps:
      - name: "Git push to helm chart repo: ${{ inputs.push }}"
        run: |
          apk add --update --no-cache yq

          helm_repo_url=${CI_SERVER_HOST}/dolby-io/infrastructure/base-images/helm.git

          # Git config
          git config --global user.name ${GIT_USER_NAME}
          git config --global user.email ${GIT_USER_EMAIL}

          if [ ${{ inputs.push }} = false ];then
            git_push_to_helm=' '
            echo "Changes will NOT be committed to helm "
          else
            git_push_to_helm='git push'
          fi

          # Setting environment
          if [[ ${ENVIRONMENT} == *"rp2"* ]]; then
            ENVIRONMENT="rp2"
          elif [[ ${ENVIRONMENT} == *"staging"* ]];then
            ENVIRONMENT="staging"
          elif [[ ${ENVIRONMENT} == *"production"* ]];then
            ENVIRONMENT="production"
          fi

          # Define project
          CI_PROJECT_NAME=$(basename ${{ github.repository }})
          if [[ ! -z ${{ inputs.override_project }} ]]
          then
            PROJECT=${{ inputs.override_project }}
          else
            case ${CI_PROJECT_NAME} in
              "developer-portal-api")
                PROJECT="dpa"
                ;;
              "media-api-server")
                PROJECT="mapi"
                ;;
              "auth-server")
                PROJECT="auth-server"
                ;;
              "segment")
                PROJECT="segment-consumer"
                ;;
              "keycloak")
                PROJECT="keycloak"
                TAG_PATH=".keycloakx.image.tag"
                TAG="${TAG}-${ENVIRONMENT}"
                ;;
              "support-utils-keycloak-callback-service")
                PROJECT="support-utils-keycloak-callback-service"
                ;;
              "Millicast-DashApi")
                PROJECT="customer-api"
                ;;
              "Millicast.Director")
                PROJECT="rts-director-api"
                ;;
              "webrtc-cdn-cdr-graphql-api")
                PROJECT="rts-graphql"
                ;;
              "wwo-app-api")
                PROJECT="wwo"
                ;;
              "rts-prom-target-generator")
                PROJECT="rts-prometheus-target-generator"
                ;;
              "internal-stream-inspector-proxy")
                PROJECT="internal-stream-inspector-proxy"
                ;;
              "dlb-streaming-recording-service")
                PROJECT="dlb-streaming-recording-service"
                ;;
              "rts-analytics-extractor")
                PROJECT="rts-analytics-extractor"
                ;;
              "rts-analytics-processor")
                PROJECT="rts-analytics-processor"
                ;;
              "rts-bandwidth-accumulator")
                PROJECT="rts-bandwidth-accumulator"
                ;;
              "rts-daily-reports")
                PROJECT="rts-daily-reports"
                ;;
              "rts-storage-accumulator")
                PROJECT="rts-storage-accumulator"
                ;;
              "rts-analytics-dumper")
                PROJECT="rts-analytics-dumper"
                ;;
              "rts-billing-notifier")
                PROJECT="rts-billing-notifier"
                ;;
              "rts-usage-uploader-informatica-sqs")
                PROJECT="rts-usage-uploader-informatica-sqs"
                ;;
              *)
                echo "Project not found: ${CI_PROJECT_NAME}"
                exit 1
                ;;
            esac
          fi

          echo "Cloning helm deployment project"
          git clone https://oauth2:${DEPLOYMENT_PAT}@${helm_repo_url}
          cd helm
          echo "Setting image ${TAG} in config/${PROJECT}/${ENVIRONMENT}.yaml"

          if [ ${{ inputs.is_cronjob }} = false ];then
            export TAG_PATH=".image.tag"
          else
            export TAG_PATH=".jobImage.tag"
          fi

          export TAG=${TAG}

          echo "PROJECT: ${PROJECT}"
          echo "TAG: ${TAG}"
          echo "TAG_PATH: ${TAG_PATH}"
          echo "ENVIRONMENT: ${ENVIRONMENT}"
          echo "PROJECT: ${PROJECT}"

          yq -i 'eval(strenv(TAG_PATH)) = strenv(TAG)' config/${PROJECT}/${ENVIRONMENT}.yaml
          git diff
          git commit -am "CI: Update ${ENVIRONMENT} ${PROJECT} ${TAG}"
          git status
          ${git_push_to_helm}

        env:
          GIT_USER_NAME: ${{ github.event.pusher.name }}
          GIT_USER_EMAIL: ${{ github.event.pusher.email }}
          DEPLOYMENT_PAT: ${{ secrets.DEPLOYMENT_PAT }}
          CI_SERVER_HOST: 'gitlab-sfo.dolby.net'
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
