name: Kaniko build and push docker image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Define path and name of the Dockerfile.'
        required: false
        type: string
        default: './Dockerfile'
      build_args:
        description: 'Build args, which are not containing secrets. They can be displayed in the build log.'
        required: false
        type: string
        default: ' '
      push:
        description: 'Set dry-run if false.'
        required: false
        type: boolean
        default: true
      ecr_repo_url:
        description: 'URL to AWS ECR repository.'
        required: true
        type: string
      millicast_tag:
        description: 'Define tag for the docker image.'
        required: true
        type: string
    secrets:
      build_args_secrets:
        description: 'Build args with secrets variables. Secrets will be masked in the build log.'
        required: false

jobs:
  kaniko:
    runs-on: [rts-dind]
    container: gcr.io/kaniko-project/executor:v1.23.0-debug
    permissions:
      contents: read
    steps:
      - name: "Build and push: ${{ inputs.push }}"
        run: |
          if [ ${{ inputs.push }} = false ];then
            push_image='--no-push'
          else
            push_image='--push-retry 3'
          fi

          if [[ ${{ github.ref_type }} == 'tag' ]];then
            context="${{ github.repositoryUrl }}#${{ github.ref }}"
          else
            context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"
          fi

          destination="${{ inputs.ecr_repo_url }}:${{ inputs.millicast_tag }}"
          build_args_all="${{ inputs.build_args}} ${{ secrets.build_args_secrets }}"

          echo "Context: ${context}"
          echo "Destination: ${destination}"

          /kaniko/executor --dockerfile=${{ inputs.dockerfile }} \
          --context=${context} \
          --destination=${destination} \
          ${push_image} \
          ${build_args_all} \
          && if [ ${{ inputs.push }} = true ];then echo "Docker image pushed to ${destination} :saluting_face:" >> $GITHUB_STEP_SUMMARY;fi
        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
