name: Kaniko build and push docker image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Define path and name of the Dockerfile.'
        required: false
        type: string
        default: './Dockerfile'
      push:
        description: 'Set dry-run if false.'
        required: false
        type: boolean
        default: true
      ecr_repo_url:
        description: 'URL to AWS ECR repository.'
        required: true
        type: string
      tag:
        description: 'Define tag for the docker image.'
        required: true
        type: string
      build_target:
        description: 'Define build target.'
        required: false
        type: string
      dotnet_project:
        description: 'Set dotnet_project to create common build args.'
        required: false
        type: boolean
        default: true

jobs:
  kaniko:
    runs-on: [rts-dind]
    container: gcr.io/kaniko-project/executor:v1.23.0-debug
    permissions:
      contents: read
    steps:
      - name: "Build and push: ${{ inputs.push }}"
        run: |
          if [ ${{ inputs.push }} = false ];then
            push_image='--no-push'
          else
            push_image='--push-retry 3'
          fi

          if [[ ${{ github.ref_type }} == 'tag' ]];then
            context="${{ github.repositoryUrl }}#${{ github.ref }}"
          else
            context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"
          fi

          # This part is creating build_args, which are common for all dotnet projects.
          if [[ ${{ inputs.dotnet_project }} ]];then
            if [[ ${{ github.ref_type }} == 'tag' ]];then
              ci_commit_tag=${{ inputs.tag }}
              ci_commit_branch=""
            else
              ci_commit_tag=""
              ci_commit_branch=${{ inputs.tag }}
            fi
            build_args="--build-arg BUILD_TARGET=${{ inputs.build_target }} --build-arg CI_COMMIT_SHA=${{ github.sha }} --build-arg CI_COMMIT_BRANCH=${ci_commit_branch} --build-arg CI_COMMIT_TAG=${ci_commit_tag} --build-arg NUGET_URL=${{ secrets.NUGET_URL }} --build-arg NUGET_USERNAME=${{ secrets.NUGET_USERNAME }} --build-arg NUGET_PASSWORD=${{ secrets.NUGET_PASSWORD }}"
          fi

          destination="${{ inputs.ecr_repo_url }}:${{ inputs.tag }}"

          echo "Context: ${context}"
          echo "Destination: ${destination}"
          echo "build_args: ${build_args}"

          /kaniko/executor --dockerfile=${{ inputs.dockerfile }} \
          --context=${context} \
          --destination=${destination} \
          ${push_image} \
          ${build_args} \
          && if [ ${{ inputs.push }} = true ];then echo "Docker image pushed to ${destination} :saluting_face:" >> $GITHUB_STEP_SUMMARY;fi
        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
