name: Publish NPM Package
on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt-mark hold firefox
          sudo add-apt-repository -y "ppa:savoury1/ffmpeg4"
          sudo apt-get update
          sudo apt-get install -y curl unzip build-essential pkg-config python3 zlib1g-dev libfreetype6-dev libjpeg62-dev libpng-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libnghttp2-dev libopenjp2-7-dev libcaca-dev libxv-dev x11proto-video-dev libgl1-mesa-dev libglu1-mesa-dev x11proto-gl-dev libxvidcore-dev libssl-dev libjack-jackd2-dev libasound2-dev libpulse-dev libsdl2-dev dvb-apps mesa-utils libx264-dev libvpx-dev libswresample-dev libgsm1-dev libopus-dev libspeex-dev libsystemd-dev libaom-dev
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: ${{ inputs.registry-url }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token }}
